version: '3.8'

services:
  app:
    image: todo
    ports:
      - "3000:5000"
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongo:27018/tododb
    depends_on:
      - mongo
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /data/db:rw

volumes:
  mongo-data:
