version: '3.8'

services:
  app:
    image: todo
    ports:
      - "3000:5000"
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongo:27018/tododb
    depends_on:
      - mongo
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
